# 指定启动Jekyll服务时的端口号，访问的地址为http://127.0.0.1:port/，不配置则默认为4000
port: 4000

# 指定并配置Markdown解析器（2016年05月01日起，GitHubPages将只支持kramdown作为唯一的Markdown引擎）
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# the base hostname & protocol for your site
# 配合页面头部<link rel="canonical" href="https://jadyer.cn/2016/10/17/first-blog/">
url: "https://jadyer.cn"
# the subpath of your site, e.g. /blog
baseurl: ""
title: 半步多
brief-intro: "玄玉的博客"

# footer下方显示的联系方式
github_username: jadyer
email: jadyer@yeah.net

# 指定页面右侧分类和标签框的链接地址
category_dir: category/
tag_dir: tag/

# 博文分页的配置
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 12

# 博文的固定链接形式（若配置成/:categories/:title.html则表示按照/分类/文章.html生成链接）
permalink: /:year/:month/:day/:title/

# 摘要分割符号（Jekyll在解析文章时便可提取摘要）
excerpt_separator: "\n\n\n\n"