#指定启动Jekyll服务时的端口号，访问的地址为http://127.0.0.1:port/，不配置则默认为4000
port: 1234

#指定并配置Markdown解析器（2016年05月01日起，GitHubPages将只支持kramdown作为唯一的Markdown引擎）
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

title: 半步多

brief-intro: "玄玉的博客"

#the subpath of your site, e.g. /blog
baseurl: ""

#配置页面头部<link rel="canonical" href="https://jadyer.github.io/2016/10/17/first-blog/">
url: "https://jadyer.github.io"

#footer下方显示的联系方式
github_username: jadyer
email: jadyer@yeah.net
weibo_username: jadyer
zhihu_username: jadyer
linkedIn_username: myjadyer
facebook_username: myjadyer
twitter_username: myjadyer

#评论（指定多说或Disqus的short_name）
#disqus_shortname: jadyer
duoshuo_shortname: jadyer

#统计（指定Baidu或Google的统计ID）
#google_analytics_id: UA-12345678-9
baidu_tongji_id: a1ec472ee05eea50838e5dab0a70c4a0

#指定页面右侧分类和标签框的链接地址
category_dir: category/
tag_dir: tag/

#博文分页的配置
gems: [jekyll-paginate]
paginate: 16

#博文的固定链接形式（若配置成/:categories/:title.html则表示按照/分类/文章.html生成链接）
permalink: /:year/:month/:day/:title/

#摘要分割符号（Jekyll在解析文章时便可提取摘要）
excerpt_separator: "\n\n\n\n"