# 指定启动Jekyll服务时的端口号，访问的地址为http://127.0.0.1:port/，不配置则默认为4000
port: 2000
exclude: ["_drafts", ".git", ".gitignore", ".jekyll-cache", "_site", "README.md"]

# 指定并配置Markdown解析器（2016年05月01日起，GitHubPages将只支持kramdown作为唯一的Markdown引擎）
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 博文分页的配置
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 12

# 供搜索引擎使用的标签<link rel="canonical">
fullurl: https://www.xuanyuv.com
title: 半步多
brief-intro: 玄玉V笔记
description: 这是一个Java技术博客，同时也记录了如Linux等周边技术。

# Baidu 和 Google 站点收录配置
# https://ziyuan.baidu.com/
baidu-site-verification: codeva-4VPtmVkV2E
# https://search.google.com/search-console/welcome
google-site-verification: MxJSZKo2T-4PXmdbLd-8uiMu1x1JsLfDFFmS3Z-JJsM

# footer下方显示的联系方式
github_username: xuanyuv
email: xuanyuv@163.com

# 摘要分割符号（Jekyll在解析文章时便可提取摘要）
excerpt_separator: "\n\n\n\n"

# 指定页面右侧分类和标签框的链接地址
category_dir: blog/category/
tag_dir: blog/tag/
# 博文的固定链接形式（若配置成/:categories/:title.html则表示按照/分类/文章.html生成链接）
permalink: /blog/:year:month:day/:title.html