# 指定启动Jekyll服务时的端口号，访问的地址为http://127.0.0.1:port/，不配置则默认为4000
port: 2000
exclude: ["_drafts", ".git", ".gitignore", ".jekyll-cache", "_site", "CNAME"]

# 指定并配置Markdown解析器（2016年05月01日起，GitHubPages将只支持kramdown作为唯一的Markdown引擎）
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# the base hostname & protocol for your site
# 配合供搜索引擎使用的页面头部<link rel="canonical" href="https://www.xuanyuv.com/blog/2016/10/17/first-blog/">
url: "https://www.xuanyuv.com"
title: 半步多
brief-intro: "玄玉V笔记"

# footer下方显示的联系方式
github_username: xuanyuv
email: xuanyuv@163.com

# 指定页面右侧分类和标签框的链接地址
category_dir: category/
tag_dir: tag/

# 博文分页的配置
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 12

# 博文的固定链接形式（若配置成/:categories/:title.html则表示按照/分类/文章.html生成链接）
permalink: /blog/:year/:month/:day/:title.html

# 摘要分割符号（Jekyll在解析文章时便可提取摘要）
excerpt_separator: "\n\n\n\n"